[workspace]
members = []
default-members = ["day-*"]
resolver = "3"

[workspace.dependencies]
nom = "*"
nom-supreme = "*"
rayon = "*"
indicatif = "*"
num = "*"
itertools = "*"
bevy = "*"
glam = "*"
rstest = "*"
