[package]
name = "day-04"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = { workspace = true }
nom-supreme = { workspace = true }
num = { workspace = true }
itertools = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
rstest.workspace = true