[package]
name = "{{ project-name }}"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = { workspace = true }
nom-supreme = { workspace = true }
num = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
rstest.workspace = true