[workspace]
members = ["day-01"]
default-members = ["day-*"]
resolver = "3"

[workspace.dependencies]
bevy = "*"
glam = "*"
indicatif = "*"
itertools = "*"
nom = "*"
nom-supreme = "*"
num = "*"
rayon = "*"
rstest = "*"
regex = "*"
