[workspace]
members = [
    "day-01",
    "day-02",
    "day-03",
    "day-04",
]
default-members = ["day-*"]
resolver = "3"

[workspace.dependencies]
bevy = "*"
glam = "*"
indicatif = "*"
itertools = "*"
nom = "*"
nom-supreme = "*"
num = "*"
rayon = "*"
regex = "*"
rstest = "*"
