# use powershell on Windows instead of `sh`
set windows-powershell

default:
  @just --list

create day:
  cargo generate --name day-{{day}} --path ./d-template

work day part:
  cargo watch -w day-{{ day }} -x "check -p day-{{ day }}" -s "just test {{ day }} {{ part }}" -s "just lint {{ day }}"

lint day:
  cargo clippy -p day-{{ day }}

test day part:
  cargo nextest run -p day-{{ day }} part{{part}}

solve day part:
  cargo run -p day-{{day}} --bin part{{part}} --release